# Generated by Django 5.2.6 on 2026-06-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('power_rating_watts', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('cooling', 'Cooling'), ('kitchen', 'Kitchen'), ('entertainment', 'Entertainment'), ('lighting', 'Lighting'), ('heating', 'Heating'), ('other', 'Other')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', '-created_at'], name='billing_app_categor_ebc094_idx')],
            },
        ),
    ]
